package wenjalan.generators;

import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.generator.ChunkGenerator;
import org.bukkit.util.noise.SimplexOctaveGenerator;

import java.util.Random;

public class GaeaGenerator extends ChunkGenerator {

    // the scale of the SimplexOctaveGenerator, larger values mean steeper terrain
    // public static final double SIMPLEX_OCTAVE_GENERATOR_SCALE = 0.005D;
    public static double simplex_octave_generator_scale;

    // constructor
    public GaeaGenerator(String id) {
        simplex_octave_generator_scale = Double.parseDouble(id);
    }

    @Override
    public ChunkData generateChunkData(World world, Random random, int chunkX, int chunkZ, BiomeGrid biome) {
        // create chunk data
        ChunkData chunkData = createChunkData(world);

        // create a SimplexOctaveGenerator to generate some terrain
        SimplexOctaveGenerator octaveGenerator = new SimplexOctaveGenerator(new Random(world.getSeed()), 8);

        // set the scale
        octaveGenerator.setScale(simplex_octave_generator_scale);

        // stores the height generated by the octave generator
        int height;

        // generate some blocks
        for (int x = 0; x < 16; x++) {
            for (int z = 0; z < 16; z++) {
                // generate next height
                height = (int) (octaveGenerator.noise(chunkX * 16 + x, chunkZ * 16 + z, 0.5D, 0.5D)
                        * 15.0D + 50.0D);

                // set blocks
                for (int y = height; y >= 0; y--) {
                    chunkData.setBlock(x, height, z, Material.STONE);
                }
            }
        }

        // return the data
        return chunkData;
    }

}
